name: git action 构建镜像
run-name: ${{ github.actor }} 构建自定义镜像
on: [push]

jobs:
  build-images:
    uses: dooubb/.github/.github/workflows/git-action.yaml@master
    secrets:
      username: ${{ secrets.docker_user_name }}
      password: ${{ secrets.docker_password }}
    with:
      allowed-author: git-bot-