name: 测试
on: [push]

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3.3.0
        with:
          repository: 'dooubb/action-test'
      - name: 测试
        run: |
            echo ${{ secrets.docker_user_name }}
            echo ${{ secrets.docker_password }}

      - name: 登录dockerhub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.docker_user_name }}  # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
          password: ${{ secrets.docker_password }}
